name: release
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  task:
    name: ${{ matrix.command }}
    runs-on: ubuntu-22.04
    environment:
      name: release
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        command:
          - release

    env:
      EXTRA_OPTS: --jobs=4 --platform=linux/amd64,linux/arm64
      EXPECTED_IMAGES: 2

    steps:
      - name: Grab the source from Git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed to determine version

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v4
        with:
          # keep this in sync with python version from base container
          python-version: "3.12" # 3.12 is default on fedora-39
          cache: "pip"

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io/${{ github.repository_owner }}

      - name: Log in to quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
          registry: quay.io

      # - name: Log in to docker.io
      #   uses: redhat-actions/podman-login@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_TOKEN }}
      #     registry: docker.io

      - name: "Run: task ${{ matrix.command }}"
        run: task ${{ matrix.command }}
